-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgpxT9JnmmTCRpapX9ZYGVVAqmEsMxXivMtZNR841V0gWgCgYIKoZIzj0DAQehRANCAASQmzUvpVWZoWAEkvgkaKDbQeLNeNn+XY65dULjTjMuFOpB7cStpA9FQ31ttwDdv6z5++jewD7I2MkDwFE8CUJD
-----END PRIVATE KEY-----